//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.02 at 01:46:08 PM BDT 
//


package ru.papillon.openws.opserver;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for candidate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="candidate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="errorMess" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="imageTags" type="{http://openws.papillon.ru/OPServer}tag" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="textTags" type="{http://openws.papillon.ru/OPServer}tag" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "candidate", propOrder = {
    "errorCode",
    "errorMess",
    "imageTags",
    "textTags"
})
public class Candidate {

    protected int errorCode;
    protected String errorMess;
    @XmlElement(nillable = true)
    protected List<Tag> imageTags;
    @XmlElement(nillable = true)
    protected List<Tag> textTags;

    /**
     * Gets the value of the errorCode property.
     * 
     */
    public int getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     */
    public void setErrorCode(int value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the errorMess property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMess() {
        return errorMess;
    }

    /**
     * Sets the value of the errorMess property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMess(String value) {
        this.errorMess = value;
    }

    /**
     * Gets the value of the imageTags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageTags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageTags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tag }
     * 
     * 
     */
    public List<Tag> getImageTags() {
        if (imageTags == null) {
            imageTags = new ArrayList<Tag>();
        }
        return this.imageTags;
    }

    /**
     * Gets the value of the textTags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textTags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextTags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tag }
     * 
     * 
     */
    public List<Tag> getTextTags() {
        if (textTags == null) {
            textTags = new ArrayList<Tag>();
        }
        return this.textTags;
    }

	public void setImageTags(List<Tag> imageTags) {
		this.imageTags = imageTags;
	}

	public void setTextTags(List<Tag> textTags) {
		this.textTags = textTags;
	}
    
    

}
