//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.02 at 01:46:08 PM BDT 
//


package ru.papillon.openws.opserver;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for findFingersRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="findFingersRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RThumbFinger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RIndexFinger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RMiddleFinger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RRingFinger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RLittleFinger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LThumbFinger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LIndexFinger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LMiddleFinger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LRingFinger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LLittleFinger" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findFingersRequest", propOrder = {
    "rThumbFinger",
    "rIndexFinger",
    "rMiddleFinger",
    "rRingFinger",
    "rLittleFinger",
    "lThumbFinger",
    "lIndexFinger",
    "lMiddleFinger",
    "lRingFinger",
    "lLittleFinger"
})
public class FindFingersRequest {

    @XmlElement(name = "RThumbFinger")
    protected String rThumbFinger;
    @XmlElement(name = "RIndexFinger")
    protected String rIndexFinger;
    @XmlElement(name = "RMiddleFinger")
    protected String rMiddleFinger;
    @XmlElement(name = "RRingFinger")
    protected String rRingFinger;
    @XmlElement(name = "RLittleFinger")
    protected String rLittleFinger;
    @XmlElement(name = "LThumbFinger")
    protected String lThumbFinger;
    @XmlElement(name = "LIndexFinger")
    protected String lIndexFinger;
    @XmlElement(name = "LMiddleFinger")
    protected String lMiddleFinger;
    @XmlElement(name = "LRingFinger")
    protected String lRingFinger;
    @XmlElement(name = "LLittleFinger")
    protected String lLittleFinger;

    /**
     * Gets the value of the rThumbFinger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRThumbFinger() {
        return rThumbFinger;
    }

    /**
     * Sets the value of the rThumbFinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRThumbFinger(String value) {
        this.rThumbFinger = value;
    }

    /**
     * Gets the value of the rIndexFinger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRIndexFinger() {
        return rIndexFinger;
    }

    /**
     * Sets the value of the rIndexFinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRIndexFinger(String value) {
        this.rIndexFinger = value;
    }

    /**
     * Gets the value of the rMiddleFinger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRMiddleFinger() {
        return rMiddleFinger;
    }

    /**
     * Sets the value of the rMiddleFinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRMiddleFinger(String value) {
        this.rMiddleFinger = value;
    }

    /**
     * Gets the value of the rRingFinger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRRingFinger() {
        return rRingFinger;
    }

    /**
     * Sets the value of the rRingFinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRRingFinger(String value) {
        this.rRingFinger = value;
    }

    /**
     * Gets the value of the rLittleFinger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRLittleFinger() {
        return rLittleFinger;
    }

    /**
     * Sets the value of the rLittleFinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRLittleFinger(String value) {
        this.rLittleFinger = value;
    }

    /**
     * Gets the value of the lThumbFinger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLThumbFinger() {
        return lThumbFinger;
    }

    /**
     * Sets the value of the lThumbFinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLThumbFinger(String value) {
        this.lThumbFinger = value;
    }

    /**
     * Gets the value of the lIndexFinger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIndexFinger() {
        return lIndexFinger;
    }

    /**
     * Sets the value of the lIndexFinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIndexFinger(String value) {
        this.lIndexFinger = value;
    }

    /**
     * Gets the value of the lMiddleFinger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLMiddleFinger() {
        return lMiddleFinger;
    }

    /**
     * Sets the value of the lMiddleFinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLMiddleFinger(String value) {
        this.lMiddleFinger = value;
    }

    /**
     * Gets the value of the lRingFinger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLRingFinger() {
        return lRingFinger;
    }

    /**
     * Sets the value of the lRingFinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLRingFinger(String value) {
        this.lRingFinger = value;
    }

    /**
     * Gets the value of the lLittleFinger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLLittleFinger() {
        return lLittleFinger;
    }

    /**
     * Sets the value of the lLittleFinger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLLittleFinger(String value) {
        this.lLittleFinger = value;
    }

}
