//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.02 at 01:46:08 PM BDT 
//


package ru.papillon.openws.opserver;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for findFingersUnspecRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="findFingersUnspecRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UnspecFinger0" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnspecFinger1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnspecFinger2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnspecFinger3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnspecFinger4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnspecFinger5" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnspecFinger6" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnspecFinger7" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnspecFinger8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnspecFinger9" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "findFingersUnspecRequest", propOrder = {
    "unspecFinger0",
    "unspecFinger1",
    "unspecFinger2",
    "unspecFinger3",
    "unspecFinger4",
    "unspecFinger5",
    "unspecFinger6",
    "unspecFinger7",
    "unspecFinger8",
    "unspecFinger9"
})
public class FindFingersUnspecRequest {

    @XmlElement(name = "UnspecFinger0")
    protected String unspecFinger0;
    @XmlElement(name = "UnspecFinger1")
    protected String unspecFinger1;
    @XmlElement(name = "UnspecFinger2")
    protected String unspecFinger2;
    @XmlElement(name = "UnspecFinger3")
    protected String unspecFinger3;
    @XmlElement(name = "UnspecFinger4")
    protected String unspecFinger4;
    @XmlElement(name = "UnspecFinger5")
    protected String unspecFinger5;
    @XmlElement(name = "UnspecFinger6")
    protected String unspecFinger6;
    @XmlElement(name = "UnspecFinger7")
    protected String unspecFinger7;
    @XmlElement(name = "UnspecFinger8")
    protected String unspecFinger8;
    @XmlElement(name = "UnspecFinger9")
    protected String unspecFinger9;

    /**
     * Gets the value of the unspecFinger0 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnspecFinger0() {
        return unspecFinger0;
    }

    /**
     * Sets the value of the unspecFinger0 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnspecFinger0(String value) {
        this.unspecFinger0 = value;
    }

    /**
     * Gets the value of the unspecFinger1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnspecFinger1() {
        return unspecFinger1;
    }

    /**
     * Sets the value of the unspecFinger1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnspecFinger1(String value) {
        this.unspecFinger1 = value;
    }

    /**
     * Gets the value of the unspecFinger2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnspecFinger2() {
        return unspecFinger2;
    }

    /**
     * Sets the value of the unspecFinger2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnspecFinger2(String value) {
        this.unspecFinger2 = value;
    }

    /**
     * Gets the value of the unspecFinger3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnspecFinger3() {
        return unspecFinger3;
    }

    /**
     * Sets the value of the unspecFinger3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnspecFinger3(String value) {
        this.unspecFinger3 = value;
    }

    /**
     * Gets the value of the unspecFinger4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnspecFinger4() {
        return unspecFinger4;
    }

    /**
     * Sets the value of the unspecFinger4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnspecFinger4(String value) {
        this.unspecFinger4 = value;
    }

    /**
     * Gets the value of the unspecFinger5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnspecFinger5() {
        return unspecFinger5;
    }

    /**
     * Sets the value of the unspecFinger5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnspecFinger5(String value) {
        this.unspecFinger5 = value;
    }

    /**
     * Gets the value of the unspecFinger6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnspecFinger6() {
        return unspecFinger6;
    }

    /**
     * Sets the value of the unspecFinger6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnspecFinger6(String value) {
        this.unspecFinger6 = value;
    }

    /**
     * Gets the value of the unspecFinger7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnspecFinger7() {
        return unspecFinger7;
    }

    /**
     * Sets the value of the unspecFinger7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnspecFinger7(String value) {
        this.unspecFinger7 = value;
    }

    /**
     * Gets the value of the unspecFinger8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnspecFinger8() {
        return unspecFinger8;
    }

    /**
     * Sets the value of the unspecFinger8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnspecFinger8(String value) {
        this.unspecFinger8 = value;
    }

    /**
     * Gets the value of the unspecFinger9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnspecFinger9() {
        return unspecFinger9;
    }

    /**
     * Sets the value of the unspecFinger9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnspecFinger9(String value) {
        this.unspecFinger9 = value;
    }

}
