//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.02 at 01:46:08 PM BDT 
//


package ru.papillon.openws.opserver;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.papillon.openws.opserver package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FindFingersUnspecRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "findFingersUnspecRequest");
    private final static QName _GetImagesRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "getImagesRequest");
    private final static QName _GetCandidateRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "getCandidateRequest");
    private final static QName _FindFingersUnspecResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "findFingersUnspecResponse");
    private final static QName _CancelFindResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "cancelFindResponse");
    private final static QName _GetInfoRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "getInfoRequest");
    private final static QName _CancelCardRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "cancelCardRequest");
    private final static QName _CancelFindRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "cancelFindRequest");
    private final static QName _CheckStatusRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "checkStatusRequest");
    private final static QName _GetInfoResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "getInfoResponse");
    private final static QName _FindFingersRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "findFingersRequest");
    private final static QName _SaveCardResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "saveCardResponse");
    private final static QName _AddImageToCardResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "addImageToCardResponse");
    private final static QName _AddImageToCardRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "addImageToCardRequest");
    private final static QName _CancelCardResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "cancelCardResponse");
    private final static QName _SaveCardRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "saveCardRequest");
    private final static QName _CheckStatusResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "checkStatusResponse");
    private final static QName _CreateCardRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "createCardRequest");
    private final static QName _GetCandidateResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "getCandidateResponse");
    private final static QName _CreateCardResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "createCardResponse");
    private final static QName _GetImagesResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "getImagesResponse");
    private final static QName _FindRequestRequest_QNAME = new QName("http://openws.papillon.ru/OPServer", "findRequestRequest");
    private final static QName _FindRequestResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "findRequestResponse");
    private final static QName _FindFingersResponse_QNAME = new QName("http://openws.papillon.ru/OPServer", "findFingersResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.papillon.openws.opserver
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FindFingersUnspecRequest }
     * 
     */
    public FindFingersUnspecRequest createFindFingersUnspecRequest() {
        return new FindFingersUnspecRequest();
    }

    /**
     * Create an instance of {@link GetImagesRequest }
     * 
     */
    public GetImagesRequest createGetImagesRequest() {
        return new GetImagesRequest();
    }

    /**
     * Create an instance of {@link GetCandidateRequest }
     * 
     */
    public GetCandidateRequest createGetCandidateRequest() {
        return new GetCandidateRequest();
    }

    /**
     * Create an instance of {@link FindFingersUnspecResponse }
     * 
     */
    public FindFingersUnspecResponse createFindFingersUnspecResponse() {
        return new FindFingersUnspecResponse();
    }

    /**
     * Create an instance of {@link CancelFindResponse }
     * 
     */
    public CancelFindResponse createCancelFindResponse() {
        return new CancelFindResponse();
    }

    /**
     * Create an instance of {@link GetInfoRequest }
     * 
     */
    public GetInfoRequest createGetInfoRequest() {
        return new GetInfoRequest();
    }

    /**
     * Create an instance of {@link CancelCardRequest }
     * 
     */
    public CancelCardRequest createCancelCardRequest() {
        return new CancelCardRequest();
    }

    /**
     * Create an instance of {@link CancelFindRequest }
     * 
     */
    public CancelFindRequest createCancelFindRequest() {
        return new CancelFindRequest();
    }

    /**
     * Create an instance of {@link CheckStatusRequest }
     * 
     */
    public CheckStatusRequest createCheckStatusRequest() {
        return new CheckStatusRequest();
    }

    /**
     * Create an instance of {@link GetInfoResponse }
     * 
     */
    public GetInfoResponse createGetInfoResponse() {
        return new GetInfoResponse();
    }

    /**
     * Create an instance of {@link FindFingersRequest }
     * 
     */
    public FindFingersRequest createFindFingersRequest() {
        return new FindFingersRequest();
    }

    /**
     * Create an instance of {@link SaveCardResponse }
     * 
     */
    public SaveCardResponse createSaveCardResponse() {
        return new SaveCardResponse();
    }

    /**
     * Create an instance of {@link AddImageToCardResponse }
     * 
     */
    public AddImageToCardResponse createAddImageToCardResponse() {
        return new AddImageToCardResponse();
    }

    /**
     * Create an instance of {@link AddImageToCardRequest }
     * 
     */
    public AddImageToCardRequest createAddImageToCardRequest() {
        return new AddImageToCardRequest();
    }

    /**
     * Create an instance of {@link CancelCardResponse }
     * 
     */
    public CancelCardResponse createCancelCardResponse() {
        return new CancelCardResponse();
    }

    /**
     * Create an instance of {@link SaveCardRequest }
     * 
     */
    public SaveCardRequest createSaveCardRequest() {
        return new SaveCardRequest();
    }

    /**
     * Create an instance of {@link CheckStatusResponse }
     * 
     */
    public CheckStatusResponse createCheckStatusResponse() {
        return new CheckStatusResponse();
    }

    /**
     * Create an instance of {@link CreateCardRequest }
     * 
     */
    public CreateCardRequest createCreateCardRequest() {
        return new CreateCardRequest();
    }

    /**
     * Create an instance of {@link GetCandidateResponse }
     * 
     */
    public GetCandidateResponse createGetCandidateResponse() {
        return new GetCandidateResponse();
    }

    /**
     * Create an instance of {@link CreateCardResponse }
     * 
     */
    public CreateCardResponse createCreateCardResponse() {
        return new CreateCardResponse();
    }

    /**
     * Create an instance of {@link GetImagesResponse }
     * 
     */
    public GetImagesResponse createGetImagesResponse() {
        return new GetImagesResponse();
    }

    /**
     * Create an instance of {@link FindRequestRequest }
     * 
     */
    public FindRequestRequest createFindRequestRequest() {
        return new FindRequestRequest();
    }

    /**
     * Create an instance of {@link FindRequestResponse }
     * 
     */
    public FindRequestResponse createFindRequestResponse() {
        return new FindRequestResponse();
    }

    /**
     * Create an instance of {@link FindFingersResponse }
     * 
     */
    public FindFingersResponse createFindFingersResponse() {
        return new FindFingersResponse();
    }

    /**
     * Create an instance of {@link Candidate }
     * 
     */
    public Candidate createCandidate() {
        return new Candidate();
    }

    /**
     * Create an instance of {@link Tag }
     * 
     */
    public Tag createTag() {
        return new Tag();
    }

    /**
     * Create an instance of {@link FindResponse }
     * 
     */
    public FindResponse createFindResponse() {
        return new FindResponse();
    }

    /**
     * Create an instance of {@link StatusResponce }
     * 
     */
    public StatusResponce createStatusResponce() {
        return new StatusResponce();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindFingersUnspecRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "findFingersUnspecRequest")
    public JAXBElement<FindFingersUnspecRequest> createFindFingersUnspecRequest(FindFingersUnspecRequest value) {
        return new JAXBElement<FindFingersUnspecRequest>(_FindFingersUnspecRequest_QNAME, FindFingersUnspecRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetImagesRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "getImagesRequest")
    public JAXBElement<GetImagesRequest> createGetImagesRequest(GetImagesRequest value) {
        return new JAXBElement<GetImagesRequest>(_GetImagesRequest_QNAME, GetImagesRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCandidateRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "getCandidateRequest")
    public JAXBElement<GetCandidateRequest> createGetCandidateRequest(GetCandidateRequest value) {
        return new JAXBElement<GetCandidateRequest>(_GetCandidateRequest_QNAME, GetCandidateRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindFingersUnspecResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "findFingersUnspecResponse")
    public JAXBElement<FindFingersUnspecResponse> createFindFingersUnspecResponse(FindFingersUnspecResponse value) {
        return new JAXBElement<FindFingersUnspecResponse>(_FindFingersUnspecResponse_QNAME, FindFingersUnspecResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelFindResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "cancelFindResponse")
    public JAXBElement<CancelFindResponse> createCancelFindResponse(CancelFindResponse value) {
        return new JAXBElement<CancelFindResponse>(_CancelFindResponse_QNAME, CancelFindResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInfoRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "getInfoRequest")
    public JAXBElement<GetInfoRequest> createGetInfoRequest(GetInfoRequest value) {
        return new JAXBElement<GetInfoRequest>(_GetInfoRequest_QNAME, GetInfoRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelCardRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "cancelCardRequest")
    public JAXBElement<CancelCardRequest> createCancelCardRequest(CancelCardRequest value) {
        return new JAXBElement<CancelCardRequest>(_CancelCardRequest_QNAME, CancelCardRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelFindRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "cancelFindRequest")
    public JAXBElement<CancelFindRequest> createCancelFindRequest(CancelFindRequest value) {
        return new JAXBElement<CancelFindRequest>(_CancelFindRequest_QNAME, CancelFindRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckStatusRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "checkStatusRequest")
    public JAXBElement<CheckStatusRequest> createCheckStatusRequest(CheckStatusRequest value) {
        return new JAXBElement<CheckStatusRequest>(_CheckStatusRequest_QNAME, CheckStatusRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "getInfoResponse")
    public JAXBElement<GetInfoResponse> createGetInfoResponse(GetInfoResponse value) {
        return new JAXBElement<GetInfoResponse>(_GetInfoResponse_QNAME, GetInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindFingersRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "findFingersRequest")
    public JAXBElement<FindFingersRequest> createFindFingersRequest(FindFingersRequest value) {
        return new JAXBElement<FindFingersRequest>(_FindFingersRequest_QNAME, FindFingersRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaveCardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "saveCardResponse")
    public JAXBElement<SaveCardResponse> createSaveCardResponse(SaveCardResponse value) {
        return new JAXBElement<SaveCardResponse>(_SaveCardResponse_QNAME, SaveCardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddImageToCardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "addImageToCardResponse")
    public JAXBElement<AddImageToCardResponse> createAddImageToCardResponse(AddImageToCardResponse value) {
        return new JAXBElement<AddImageToCardResponse>(_AddImageToCardResponse_QNAME, AddImageToCardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddImageToCardRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "addImageToCardRequest")
    public JAXBElement<AddImageToCardRequest> createAddImageToCardRequest(AddImageToCardRequest value) {
        return new JAXBElement<AddImageToCardRequest>(_AddImageToCardRequest_QNAME, AddImageToCardRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelCardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "cancelCardResponse")
    public JAXBElement<CancelCardResponse> createCancelCardResponse(CancelCardResponse value) {
        return new JAXBElement<CancelCardResponse>(_CancelCardResponse_QNAME, CancelCardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaveCardRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "saveCardRequest")
    public JAXBElement<SaveCardRequest> createSaveCardRequest(SaveCardRequest value) {
        return new JAXBElement<SaveCardRequest>(_SaveCardRequest_QNAME, SaveCardRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CheckStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "checkStatusResponse")
    public JAXBElement<CheckStatusResponse> createCheckStatusResponse(CheckStatusResponse value) {
        return new JAXBElement<CheckStatusResponse>(_CheckStatusResponse_QNAME, CheckStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCardRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "createCardRequest")
    public JAXBElement<CreateCardRequest> createCreateCardRequest(CreateCardRequest value) {
        return new JAXBElement<CreateCardRequest>(_CreateCardRequest_QNAME, CreateCardRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCandidateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "getCandidateResponse")
    public JAXBElement<GetCandidateResponse> createGetCandidateResponse(GetCandidateResponse value) {
        return new JAXBElement<GetCandidateResponse>(_GetCandidateResponse_QNAME, GetCandidateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateCardResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "createCardResponse")
    public JAXBElement<CreateCardResponse> createCreateCardResponse(CreateCardResponse value) {
        return new JAXBElement<CreateCardResponse>(_CreateCardResponse_QNAME, CreateCardResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetImagesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "getImagesResponse")
    public JAXBElement<GetImagesResponse> createGetImagesResponse(GetImagesResponse value) {
        return new JAXBElement<GetImagesResponse>(_GetImagesResponse_QNAME, GetImagesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindRequestRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "findRequestRequest")
    public JAXBElement<FindRequestRequest> createFindRequestRequest(FindRequestRequest value) {
        return new JAXBElement<FindRequestRequest>(_FindRequestRequest_QNAME, FindRequestRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindRequestResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "findRequestResponse")
    public JAXBElement<FindRequestResponse> createFindRequestResponse(FindRequestResponse value) {
        return new JAXBElement<FindRequestResponse>(_FindRequestResponse_QNAME, FindRequestResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindFingersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openws.papillon.ru/OPServer", name = "findFingersResponse")
    public JAXBElement<FindFingersResponse> createFindFingersResponse(FindFingersResponse value) {
        return new JAXBElement<FindFingersResponse>(_FindFingersResponse_QNAME, FindFingersResponse.class, null, value);
    }

}
